import { Game, AppUser } from './types';

export const DEMO_USERS: { customer: AppUser; seller: AppUser } = {
  customer: {
    userId: 'user-customer-1',
    name: 'Elena Vance',
    email: 'elena@gamenest.com',
    role: 'customer',
    createdAt: new Date().toISOString(),
  },
  seller: {
    userId: 'seller-demo',
    name: 'Chronos Vault Store',
    email: 'seller@gamenest.com',
    role: 'seller',
    storeName: 'Chronos Vault Store',
    createdAt: new Date().toISOString(),
  },
};

export const INITIAL_GAMES: Game[] = [
  {
    gameId: 'game-1',
    sellerId: 'seller-1',
    sellerName: 'Chronos Games',
    title: 'Chrono Odyssey',
    subtitle: 'PC Steam Key • Global Activation',
    description: 'An open-world MMORPG set in a universe where time and space collapse. Experience seamless real-time combat, manipulate time mechanics during encounters, and explore a vast fantasy world.',
    genre: 'Action RPG',
    platform: 'PC (Steam)',
    price: 89.99,
    originalPrice: 99.99,
    coverImage: '/images/chronos_hero.png',
    badge: 'limited',
    stock: 24,
    rating: 4.9,
    status: 'active',
    releaseDate: '2025',
    publisher: 'NPIXEL',
    features: [
      'Time Manipulation Combat Mechanics',
      'Seamless Open World without Loading Screens',
      'Unreal Engine 5 Next-Gen Graphics',
      'Multiplayer Raids & World Bosses',
    ],
    systemReqs: {
      os: 'Windows 10/11 64-bit',
      processor: 'Intel Core i7-10700K or AMD Ryzen 7 3700X',
      memory: '16 GB RAM',
      graphics: 'NVIDIA GeForce RTX 3070 (8GB) / AMD Radeon RX 6800',
      storage: '90 GB SSD',
    },
    createdAt: new Date().toISOString(),
  },
  {
    gameId: 'game-2',
    sellerId: 'seller-2',
    sellerName: 'FromSoft Vault',
    title: 'Elden Ring: Shadow of the Erdtree',
    subtitle: 'PS5 Digital Code • North America',
    description: 'Journey to the Land of Shadow to unravel dark secrets and face formidable new bosses. Expand your Lands Between experience with new weapons, armor, and magic spells.',
    genre: 'Dark Fantasy',
    platform: 'PlayStation 5',
    price: 59.99,
    coverImage: '/images/elden_phantom.png',
    badge: 'new',
    stock: 50,
    rating: 4.95,
    status: 'active',
    releaseDate: '2024',
    publisher: 'Bandai Namco Entertainment',
    features: [
      'Expansive New Land of Shadow Map',
      'Over 100 New Weapons & Weapon Skills',
      'Challenging Boss Encounters',
      'Rich Lore by Hidetaka Miyazaki',
    ],
    systemReqs: {
      os: 'PlayStation 5 System Software',
      processor: 'Custom AMD Zen 2',
      memory: '16 GB GDDR6',
      graphics: 'Custom RDNA 2',
      storage: '60 GB SSD',
    },
    createdAt: new Date().toISOString(),
  },
  {
    gameId: 'game-3',
    sellerId: 'seller-3',
    sellerName: 'CDPR Store',
    title: 'Cyberpunk 2077: Phantom Liberty',
    subtitle: 'PC GOG / Steam Key • Global',
    description: 'A spy-thriller expansion for Cyberpunk 2077. Return as cyber-enhanced mercenary V and embark on a high-stakes mission of espionage and survival in Dogtown.',
    genre: 'Sci-Fi Cyberpunk',
    platform: 'PC (Steam)',
    price: 29.99,
    originalPrice: 39.99,
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    badge: 'sale',
    stock: 100,
    rating: 4.8,
    status: 'active',
    releaseDate: '2023',
    publisher: 'CD PROJEKT RED',
    features: [
      'New Dogtown Walled District',
      'Relic Skill Tree with Cyberware Powers',
      'Vehicle Combat & Relic Perks',
      'Starring Idris Elba as Solomon Reed',
    ],
    systemReqs: {
      os: 'Windows 10 64-bit',
      processor: 'Intel Core i7-12700K or AMD Ryzen 7 7800X3D',
      memory: '16 GB RAM',
      graphics: 'NVIDIA RTX 3080 / AMD RX 7900 XT',
      storage: '70 GB NVMe SSD',
    },
    createdAt: new Date().toISOString(),
  },
  {
    gameId: 'game-4',
    sellerId: 'seller-1',
    sellerName: 'Chronos Games',
    title: 'Starfield: Constellation Edition',
    subtitle: 'Xbox Series X/S Digital Key',
    description: 'Embark on an epic space adventure from Bethesda Game Studios. Explore over 1,000 planets, build custom starships, and uncover the mysteries of humanity.',
    genre: 'Sci-Fi Cyberpunk',
    platform: 'Xbox Series X',
    price: 69.99,
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    badge: 'new',
    stock: 15,
    rating: 4.6,
    status: 'active',
    releaseDate: '2023',
    publisher: 'Bethesda Softworks',
    features: [
      'Explore 1,000+ Fully Realized Planets',
      'Custom Ship Building & Flight Simulation',
      'Outpost Construction & Resource Trading',
      'Deep Faction Storylines & Companions',
    ],
    systemReqs: {
      os: 'Xbox Series X / Windows 11',
      processor: 'AMD Ryzen 5 3600X or Intel i5-10600K',
      memory: '16 GB RAM',
      graphics: 'AMD Radeon RX 6800 XT / NVIDIA RTX 3070',
      storage: '125 GB SSD',
    },
    createdAt: new Date().toISOString(),
  },
  {
    gameId: 'game-5',
    sellerId: 'seller-4',
    sellerName: 'Turn10 Store',
    title: 'Forza Horizon 5: Premium Edition',
    subtitle: 'PC / Xbox Play Anywhere Code',
    description: 'Explore the vibrant open world landscapes of Mexico with unlimited driving action in hundreds of the world’s greatest cars.',
    genre: 'Racing',
    platform: 'PC (Steam)',
    price: 49.99,
    originalPrice: 99.99,
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80',
    badge: 'sale',
    stock: 80,
    rating: 4.85,
    status: 'active',
    releaseDate: '2021',
    publisher: 'Xbox Game Studios',
    features: [
      'Over 700 Authentically Rendered Cars',
      'Dynamic Seasons & Weather Systems',
      'EventLab Gameplay Toolset',
      '4K 60FPS High Frame Rate Racing',
    ],
    systemReqs: {
      os: 'Windows 10/11',
      processor: 'Intel i7-10700K or AMD Ryzen 7 3800X',
      memory: '16 GB RAM',
      graphics: 'NVIDIA RTX 3070 / AMD RX 6800',
      storage: '110 GB SSD',
    },
    createdAt: new Date().toISOString(),
  },
  {
    gameId: 'game-6',
    sellerId: 'seller-5',
    sellerName: 'Square Enix Hub',
    title: 'Final Fantasy XVI',
    subtitle: 'PS5 Digital Code • Global',
    description: 'An epic dark fantasy world where the fate of the land is decided by the Eikons and the Dominants who wield them. Follow Clive Rosfield in a tale of revenge and fate.',
    genre: 'Action RPG',
    platform: 'PlayStation 5',
    price: 69.99,
    coverImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80',
    badge: 'new',
    stock: 85,
    rating: 4.75,
    status: 'active',
    releaseDate: '2023',
    publisher: 'Square Enix',
    features: [
      'High-Octane Real-Time Eikon Battles',
      'Gripping Story by Kazutoyo Maehiro',
      'Combat System Designed by Ryota Suzuki',
      'PS5 DualSense Haptic Feedback',
    ],
    systemReqs: {
      os: 'PlayStation 5 System Software',
      processor: 'Custom AMD Zen 2',
      memory: '16 GB GDDR6',
      graphics: 'Custom RDNA 2',
      storage: '90 GB SSD',
    },
    createdAt: new Date().toISOString(),
  },
];
